name: SpotiTool Automation

on:
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        run: |
          echo "BEATPORT_USERNAME=${{ secrets.BEATPORT_USERNAME }}" >> $GITHUB_ENV
          echo "BEATPORT_PASSWORD=${{ secrets.BEATPORT_PASSWORD }}" >> $GITHUB_ENV
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "SPOTIFY_REDIRECT_URI=http://127.0.0.1:9090" >> $GITHUB_ENV

      - name: Run SpotiTool script
        run: |
          source venv/bin/activate
          python SpotiTool.py

      - name: Upload last scan file
        uses: actions/upload-artifact@v4
        with:
          name: last_scan
          path: last_scan.json
          retention-days: 7
